// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: board.sql

package database

import (
	"context"
	"encoding/json"
)

const createMove = `-- name: CreateMove :exec
INSERT INTO board(board, move, whiteTime, blackTime, matchId, created_at)
VALUES(
  $1,
  $1,
  $1,
  $1,
  $1,
  NOW()
)
`

func (q *Queries) CreateMove(ctx context.Context, board json.RawMessage) error {
	_, err := q.db.ExecContext(ctx, createMove, board)
	return err
}
