// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: matches_users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMatchUser = `-- name: CreateMatchUser :exec
INSERT INTO matches_users(match_id, user_id)
VALUES(
  $1,
  $2
)
`

type CreateMatchUserParams struct {
	MatchID int32
	UserID  uuid.UUID
}

func (q *Queries) CreateMatchUser(ctx context.Context, arg CreateMatchUserParams) error {
	_, err := q.db.ExecContext(ctx, createMatchUser, arg.MatchID, arg.UserID)
	return err
}

const deleteMatchUser = `-- name: DeleteMatchUser :exec
DELETE FROM matches_users WHERE user_id = $1 AND match_id = $2
`

type DeleteMatchUserParams struct {
	UserID  uuid.UUID
	MatchID int32
}

func (q *Queries) DeleteMatchUser(ctx context.Context, arg DeleteMatchUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteMatchUser, arg.UserID, arg.MatchID)
	return err
}
