// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: matches.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches(white, black, full_time, user_id, created_at)
VALUES(
  $1,
  $2,
  $3,
  $4,
  NOW()
) RETURNING id
`

type CreateMatchParams struct {
	White    string
	Black    string
	FullTime int32
	UserID   uuid.UUID
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createMatch,
		arg.White,
		arg.Black,
		arg.FullTime,
		arg.UserID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
