// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Board struct {
	ID        int32
	Board     json.RawMessage
	Move      string
	Whitetime int32
	Blacktime int32
	MatchID   int32
	CreatedAt time.Time
}

type Match struct {
	ID        int32
	White     string
	Black     string
	FullTime  int32
	UserID    uuid.UUID
	CreatedAt time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	Email          string
	HashedPassword string
}
