// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex justify-between items-center mb-6\"><h2 class=\"text-xl font-semibold text-gray-100\" id=\"modal-title\">Login</h2><button hx-get=\"/close-modal\" class=\"text-gray-400 hover:text-gray-200 text-2xl leading-none\">&times;</button></div><form id=\"auth-form\" hx-post=\"/auth-login\" hx-target=\"#modal-content\" hx-swap=\"none\" class=\"space-y-4\"><div><div><label class=\"block text-sm font-medium text-gray-300\">Email</label> <input type=\"email\" name=\"email\" required autocomplete=\"email\" class=\"mt-1 w-full bg-[#2c2926] border border-gray-600 rounded px-3 py-2 text-gray-100 focus:outline-none focus:ring-2 focus:ring-amber-600\"></div><div id=\"password\" class=\"mt-2\"><label class=\"block text-sm font-medium text-gray-300\">Password</label> <input type=\"password\" name=\"password\" required autocomplete=\"current-password\" class=\"mt-1 w-full bg-[#2c2926] border border-gray-600 rounded px-3 py-2 text-gray-100 focus:outline-none focus:ring-2 focus:ring-amber-600\"></div><div id=\"incorrect-password\"></div><button type=\"submit\" class=\"w-full mt-4 bg-emerald-500 hover:bg-emerald-600 text-white py-2 rounded transition\">Login</button></div></form><div class=\"text-sm text-center mt-4 text-gray-300\">Don't have an account? <button hx-get=\"/signup-modal\" hx-target=\"#modal-content\" hx-swap=\"innerHTML\" class=\"text-amber-400 hover:underline\">Sign up</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
