package main

import "github.com/NikolaTosic-sudo/chess-live/components/board"

func MakeBoard() map[string]board.Square {
	board := map[string]board.Square{
		"1a": {
			Selected:    false,
			Coordinates: [2]int{0, 0},
			Color:       "#b58863",
		},
		"2a": {
			Selected:    false,
			Coordinates: [2]int{100, 0},
			Color:       "#f0d9b5",
		},
		"3a": {
			Selected:    false,
			Coordinates: [2]int{200, 0},
			Color:       "#b58863",
		},
		"4a": {
			Selected:    false,
			Coordinates: [2]int{300, 0},
			Color:       "#f0d9b5",
		},
		"5a": {
			Selected:    false,
			Coordinates: [2]int{400, 0},
			Color:       "#b58863",
		},
		"6a": {
			Selected:    false,
			Coordinates: [2]int{500, 0},
			Color:       "#f0d9b5",
		},
		"7a": {
			Selected:    false,
			Coordinates: [2]int{600, 0},
			Color:       "#b58863",
		},
		"8a": {
			Selected:    false,
			Coordinates: [2]int{700, 0},
			Color:       "#f0d9b5",
		},
		"1b": {
			Selected:    false,
			Coordinates: [2]int{0, 100},
			Color:       "#f0d9b5",
		},
		"2b": {
			Selected:    false,
			Coordinates: [2]int{100, 100},
			Color:       "#b58863",
		},
		"3b": {
			Selected:    false,
			Coordinates: [2]int{200, 100},
			Color:       "#f0d9b5",
		},
		"4b": {
			Selected:    false,
			Coordinates: [2]int{300, 100},
			Color:       "#b58863",
		},
		"5b": {
			Selected:    false,
			Coordinates: [2]int{400, 100},
			Color:       "#f0d9b5",
		},
		"6b": {
			Selected:    false,
			Coordinates: [2]int{500, 100},
			Color:       "#b58863",
		},
		"7b": {
			Selected:    false,
			Coordinates: [2]int{600, 100},
			Color:       "#f0d9b5",
		},
		"8b": {
			Selected:    false,
			Coordinates: [2]int{700, 100},
			Color:       "#b58863",
		},
		"1c": {
			Selected:    false,
			Coordinates: [2]int{0, 200},
			Color:       "#b58863",
		},
		"2c": {
			Selected:    false,
			Coordinates: [2]int{100, 200},
			Color:       "#f0d9b5",
		},
		"3c": {
			Selected:    false,
			Coordinates: [2]int{200, 200},
			Color:       "#b58863",
		},
		"4c": {
			Selected:    false,
			Coordinates: [2]int{300, 200},
			Color:       "#f0d9b5",
		},
		"5c": {
			Selected:    false,
			Coordinates: [2]int{400, 200},
			Color:       "#b58863",
		},
		"6c": {
			Selected:    false,
			Coordinates: [2]int{500, 200},
			Color:       "#f0d9b5",
		},
		"7c": {
			Selected:    false,
			Coordinates: [2]int{600, 200},
			Color:       "#b58863",
		},
		"8c": {
			Selected:    false,
			Coordinates: [2]int{700, 200},
			Color:       "#f0d9b5",
		},
		"1d": {
			Selected:    false,
			Coordinates: [2]int{0, 300},
			Color:       "#f0d9b5",
		},
		"2d": {
			Selected:    false,
			Coordinates: [2]int{100, 300},
			Color:       "#b58863",
		},
		"3d": {
			Selected:    false,
			Coordinates: [2]int{200, 300},
			Color:       "#f0d9b5",
		},
		"4d": {
			Selected:    false,
			Coordinates: [2]int{300, 300},
			Color:       "#b58863",
		},
		"5d": {
			Selected:    false,
			Coordinates: [2]int{400, 300},
			Color:       "#f0d9b5",
		},
		"6d": {
			Selected:    false,
			Coordinates: [2]int{500, 300},
			Color:       "#b58863",
		},
		"7d": {
			Selected:    false,
			Coordinates: [2]int{600, 300},
			Color:       "#f0d9b5",
		},
		"8d": {
			Selected:    false,
			Coordinates: [2]int{700, 300},
			Color:       "#b58863",
		},
		"1e": {
			Selected:    false,
			Coordinates: [2]int{0, 400},
			Color:       "#b58863",
		},
		"2e": {
			Selected:    false,
			Coordinates: [2]int{100, 400},
			Color:       "#f0d9b5",
		},
		"3e": {
			Selected:    false,
			Coordinates: [2]int{200, 400},
			Color:       "#b58863",
		},
		"4e": {
			Selected:    false,
			Coordinates: [2]int{300, 400},
			Color:       "#f0d9b5",
		},
		"5e": {
			Selected:    false,
			Coordinates: [2]int{400, 400},
			Color:       "#b58863",
		},
		"6e": {
			Selected:    false,
			Coordinates: [2]int{500, 400},
			Color:       "#f0d9b5",
		},
		"7e": {
			Selected:    false,
			Coordinates: [2]int{600, 400},
			Color:       "#b58863",
		},
		"8e": {
			Selected:    false,
			Coordinates: [2]int{700, 400},
			Color:       "#f0d9b5",
		},
		"1f": {
			Selected:    false,
			Coordinates: [2]int{0, 500},
			Color:       "#f0d9b5",
		},
		"2f": {
			Selected:    false,
			Coordinates: [2]int{100, 500},
			Color:       "#b58863",
		},
		"3f": {
			Selected:    false,
			Coordinates: [2]int{200, 500},
			Color:       "#f0d9b5",
		},
		"4f": {
			Selected:    false,
			Coordinates: [2]int{300, 500},
			Color:       "#b58863",
		},
		"5f": {
			Selected:    false,
			Coordinates: [2]int{400, 500},
			Color:       "#f0d9b5",
		},
		"6f": {
			Selected:    false,
			Coordinates: [2]int{500, 500},
			Color:       "#b58863",
		},
		"7f": {
			Selected:    false,
			Coordinates: [2]int{600, 500},
			Color:       "#f0d9b5",
		},
		"8f": {
			Selected:    false,
			Coordinates: [2]int{700, 500},
			Color:       "#b58863",
		},
		"1g": {
			Selected:    false,
			Coordinates: [2]int{0, 600},
			Color:       "#b58863",
		},
		"2g": {
			Selected:    false,
			Coordinates: [2]int{100, 600},
			Color:       "#f0d9b5",
		},
		"3g": {
			Selected:    false,
			Coordinates: [2]int{200, 600},
			Color:       "#b58863",
		},
		"4g": {
			Selected:    false,
			Coordinates: [2]int{300, 600},
			Color:       "#f0d9b5",
		},
		"5g": {
			Selected:    false,
			Coordinates: [2]int{400, 600},
			Color:       "#b58863",
		},
		"6g": {
			Selected:    false,
			Coordinates: [2]int{500, 600},
			Color:       "#f0d9b5",
		},
		"7g": {
			Selected:    false,
			Coordinates: [2]int{600, 600},
			Color:       "#b58863",
		},
		"8g": {
			Selected:    false,
			Coordinates: [2]int{700, 600},
			Color:       "#f0d9b5",
		},
		"1h": {
			Selected:    false,
			Coordinates: [2]int{0, 700},
			Color:       "#f0d9b5",
		},
		"2h": {
			Selected:    false,
			Coordinates: [2]int{100, 700},
			Color:       "#b58863",
		},
		"3h": {
			Selected:    false,
			Coordinates: [2]int{200, 700},
			Color:       "#f0d9b5",
		},
		"4h": {
			Selected:    false,
			Coordinates: [2]int{300, 700},
			Color:       "#b58863",
		},
		"5h": {
			Selected:    false,
			Coordinates: [2]int{400, 700},
			Color:       "#f0d9b5",
		},
		"6h": {
			Selected:    false,
			Coordinates: [2]int{500, 700},
			Color:       "#b58863",
		},
		"7h": {
			Selected:    false,
			Coordinates: [2]int{600, 700},
			Color:       "#f0d9b5",
		},
		"8h": {
			Selected:    false,
			Coordinates: [2]int{700, 700},
			Color:       "#b58863",
		},
	}
	return board
}

func MakePieces() map[string]board.Piece {
	pieces := map[string]board.Piece{
		"right_black_rook": {
			Name:       "right_black_rook",
			Image:      "black_rook",
			Tile:       "8a",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 0}, {0, 1}, {-1, 0}, {0, -1}},
			Moved:      false,
		},
		"right_black_knight": {
			Name:       "right_black_knight",
			Image:      "black_knight",
			Tile:       "8b",
			IsWhite:    false,
			LegalMoves: [][]int{{2, 1}, {2, -1}, {1, 2}, {1, -2}, {-1, 2}, {-1, -2}, {-2, 1}, {-2, -1}},
			MovesOnce:  true,
			Moved:      false,
		},
		"right_black_bishop": {
			Name:       "right_black_bishop",
			Image:      "black_bishop",
			Tile:       "8c",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}},
			Moved:      false,
		},
		"black_queen": {
			Name:       "black_queen",
			Image:      "black_queen",
			Tile:       "8d",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}, {1, 0}, {0, 1}, {-1, 0}, {0, -1}},
			Moved:      false,
		},
		"black_king": {
			Name:       "black_king",
			Image:      "black_king",
			Tile:       "8e",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}, {1, 0}, {0, 1}, {-1, 0}, {0, -1}},
			Moved:      false,
			MovesOnce:  true,
			IsKing:     true,
		},
		"left_black_bishop": {
			Name:       "left_black_bishop",
			Image:      "black_bishop",
			Tile:       "8f",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}},
			Moved:      false,
		},
		"left_black_knight": {
			Name:       "left_black_knight",
			Image:      "black_knight",
			Tile:       "8g",
			IsWhite:    false,
			LegalMoves: [][]int{{2, 1}, {2, -1}, {1, 2}, {1, -2}, {-1, 2}, {-1, -2}, {-2, 1}, {-2, -1}},
			MovesOnce:  true,
			Moved:      false,
		},
		"left_black_rook": {
			Name:       "left_black_rook",
			Image:      "black_rook",
			Tile:       "8h",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 0}, {0, 1}, {-1, 0}, {0, -1}},
			Moved:      false,
		},
		"black_pawn_1": {
			Name:       "black_pawn_1",
			Image:      "black_pawn",
			Tile:       "7a",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"black_pawn_2": {
			Name:       "black_pawn_2",
			Image:      "black_pawn",
			Tile:       "7b",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"black_pawn_3": {
			Name:       "black_pawn_3",
			Image:      "black_pawn",
			Tile:       "7c",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"black_pawn_4": {
			Name:       "black_pawn_4",
			Image:      "black_pawn",
			Tile:       "7d",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"black_pawn_5": {
			Name:       "black_pawn_5",
			Image:      "black_pawn",
			Tile:       "7e",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"black_pawn_6": {
			Name:       "black_pawn_6",
			Image:      "black_pawn",
			Tile:       "7f",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"black_pawn_7": {
			Name:       "black_pawn_7",
			Image:      "black_pawn",
			Tile:       "7g",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"black_pawn_8": {
			Name:       "black_pawn_8",
			Image:      "black_pawn",
			Tile:       "7h",
			IsWhite:    false,
			LegalMoves: [][]int{{1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"right_white_rook": {
			Name:       "right_white_rook",
			Image:      "white_rook",
			Tile:       "1a",
			IsWhite:    true,
			LegalMoves: [][]int{{1, 0}, {0, 1}, {-1, 0}, {0, -1}},
			Moved:      false,
		},
		"right_white_knight": {
			Name:       "right_white_knight",
			Image:      "white_knight",
			Tile:       "1b",
			IsWhite:    true,
			LegalMoves: [][]int{{2, 1}, {2, -1}, {1, 2}, {1, -2}, {-1, 2}, {-1, -2}, {-2, 1}, {-2, -1}},
			MovesOnce:  true,
			Moved:      false,
		},
		"right_white_bishop": {
			Name:       "right_white_bishop",
			Image:      "white_bishop",
			Tile:       "1c",
			IsWhite:    true,
			LegalMoves: [][]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}},
			Moved:      false,
		},
		"white_queen": {
			Name:       "white_queen",
			Image:      "white_queen",
			Tile:       "1d",
			IsWhite:    true,
			LegalMoves: [][]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}, {1, 0}, {0, 1}, {-1, 0}, {0, -1}},
			Moved:      false,
		},
		"white_king": {
			Name:       "white_king",
			Image:      "white_king",
			Tile:       "1e",
			IsWhite:    true,
			LegalMoves: [][]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}, {1, 0}, {0, 1}, {-1, 0}, {0, -1}},
			MovesOnce:  true,
			Moved:      false,
			IsKing:     true,
		},
		"left_white_bishop": {
			Name:       "left_white_bishop",
			Image:      "white_bishop",
			Tile:       "1f",
			IsWhite:    true,
			LegalMoves: [][]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}},
			Moved:      false,
		},
		"left_white_knight": {
			Name:       "left_white_knight",
			Image:      "white_knight",
			Tile:       "1g",
			IsWhite:    true,
			LegalMoves: [][]int{{2, 1}, {2, -1}, {1, 2}, {1, -2}, {-1, 2}, {-1, -2}, {-2, 1}, {-2, -1}},
			MovesOnce:  true,
			Moved:      false,
		},
		"left_white_rook": {
			Name:       "left_white_rook",
			Image:      "white_rook",
			Tile:       "1h",
			IsWhite:    true,
			LegalMoves: [][]int{{1, 0}, {0, 1}, {-1, 0}, {0, -1}},
			Moved:      false,
		},
		"white_pawn_1": {
			Name:       "white_pawn_1",
			Image:      "white_pawn",
			Tile:       "2a",
			IsWhite:    true,
			LegalMoves: [][]int{{-1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"white_pawn_2": {
			Name:       "white_pawn_2",
			Image:      "white_pawn",
			Tile:       "2b",
			IsWhite:    true,
			LegalMoves: [][]int{{-1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"white_pawn_3": {
			Name:       "white_pawn_3",
			Image:      "white_pawn",
			Tile:       "2c",
			IsWhite:    true,
			LegalMoves: [][]int{{-1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"white_pawn_4": {
			Name:       "white_pawn_4",
			Image:      "white_pawn",
			Tile:       "2d",
			IsWhite:    true,
			LegalMoves: [][]int{{-1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"white_pawn_5": {
			Name:       "white_pawn_5",
			Image:      "white_pawn",
			Tile:       "2e",
			IsWhite:    true,
			LegalMoves: [][]int{{-1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"white_pawn_6": {
			Name:       "white_pawn_6",
			Image:      "white_pawn",
			Tile:       "2f",
			IsWhite:    true,
			LegalMoves: [][]int{{-1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"white_pawn_7": {
			Name:       "white_pawn_7",
			Image:      "white_pawn",
			Tile:       "2g",
			IsWhite:    true,
			LegalMoves: [][]int{{-1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
		"white_pawn_8": {
			Name:       "white_pawn_8",
			Image:      "white_pawn",
			Tile:       "2h",
			IsWhite:    true,
			LegalMoves: [][]int{{-1, 0}},
			MovesOnce:  true,
			Moved:      false,
			IsPawn:     true,
		},
	}
	return pieces
}
