package main

import "github.com/NikolaTosic-sudo/chess-live/components/board"

func MakeBoard() map[string]board.Square {
	board := map[string]board.Square{
		"1a": {
			Piece:       "white_rook",
			Selected:    false,
			Coordinates: [2]int{0, 0},
			Color:       "#b58863",
		},
		"2a": {
			Piece:       "white_pawn",
			Selected:    false,
			Coordinates: [2]int{100, 0},
			Color:       "#f0d9b5",
		},
		"3a": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{200, 0},
			Color:       "#b58863",
		},
		"4a": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{300, 0},
			Color:       "#f0d9b5",
		},
		"5a": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{400, 0},
			Color:       "#b58863",
		},
		"6a": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{500, 0},
			Color:       "#f0d9b5",
		},
		"7a": {
			Piece:       "black_pawn",
			Selected:    false,
			Coordinates: [2]int{600, 0},
			Color:       "#b58863",
		},
		"8a": {
			Piece:       "black_rook",
			Selected:    false,
			Coordinates: [2]int{700, 0},
			Color:       "#f0d9b5",
		},
		"1b": {
			Piece:       "white_knight",
			Selected:    false,
			Coordinates: [2]int{0, 100},
			Color:       "#f0d9b5",
		},
		"2b": {
			Piece:       "white_pawn",
			Selected:    false,
			Coordinates: [2]int{100, 100},
			Color:       "#b58863",
		},
		"3b": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{200, 100},
			Color:       "#f0d9b5",
		},
		"4b": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{300, 100},
			Color:       "#b58863",
		},
		"5b": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{400, 100},
			Color:       "#f0d9b5",
		},
		"6b": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{500, 100},
			Color:       "#b58863",
		},
		"7b": {
			Piece:       "black_pawn",
			Selected:    false,
			Coordinates: [2]int{600, 100},
			Color:       "#f0d9b5",
		},
		"8b": {
			Piece:       "black_knight",
			Selected:    false,
			Coordinates: [2]int{700, 100},
			Color:       "#b58863",
		},
		"1c": {
			Piece:       "white_bishop",
			Selected:    false,
			Coordinates: [2]int{0, 200},
			Color:       "#b58863",
		},
		"2c": {
			Piece:       "white_pawn",
			Selected:    false,
			Coordinates: [2]int{100, 200},
			Color:       "#f0d9b5",
		},
		"3c": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{200, 200},
			Color:       "#b58863",
		},
		"4c": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{300, 200},
			Color:       "#f0d9b5",
		},
		"5c": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{400, 200},
			Color:       "#b58863",
		},
		"6c": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{500, 200},
			Color:       "#f0d9b5",
		},
		"7c": {
			Piece:       "black_pawn",
			Selected:    false,
			Coordinates: [2]int{600, 200},
			Color:       "#b58863",
		},
		"8c": {
			Piece:       "black_bishop",
			Selected:    false,
			Coordinates: [2]int{700, 200},
			Color:       "#f0d9b5",
		},
		"1d": {
			Piece:       "white_queen",
			Selected:    false,
			Coordinates: [2]int{0, 300},
			Color:       "#f0d9b5",
		},
		"2d": {
			Piece:       "white_pawn",
			Selected:    false,
			Coordinates: [2]int{100, 300},
			Color:       "#b58863",
		},
		"3d": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{200, 300},
			Color:       "#f0d9b5",
		},
		"4d": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{300, 300},
			Color:       "#b58863",
		},
		"5d": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{400, 300},
			Color:       "#f0d9b5",
		},
		"6d": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{500, 300},
			Color:       "#b58863",
		},
		"7d": {
			Piece:       "black_pawn",
			Selected:    false,
			Coordinates: [2]int{600, 300},
			Color:       "#f0d9b5",
		},
		"8d": {
			Piece:       "black_queen",
			Selected:    false,
			Coordinates: [2]int{700, 300},
			Color:       "#b58863",
		},
		"1e": {
			Piece:       "white_king",
			Selected:    false,
			Coordinates: [2]int{0, 400},
			Color:       "#b58863",
		},
		"2e": {
			Piece:       "white_pawn",
			Selected:    false,
			Coordinates: [2]int{100, 400},
			Color:       "#f0d9b5",
		},
		"3e": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{200, 400},
			Color:       "#b58863",
		},
		"4e": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{300, 400},
			Color:       "#f0d9b5",
		},
		"5e": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{400, 400},
			Color:       "#b58863",
		},
		"6e": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{500, 400},
			Color:       "#f0d9b5",
		},
		"7e": {
			Piece:       "black_pawn",
			Selected:    false,
			Coordinates: [2]int{600, 400},
			Color:       "#b58863",
		},
		"8e": {
			Piece:       "black_king",
			Selected:    false,
			Coordinates: [2]int{700, 400},
			Color:       "#f0d9b5",
		},
		"1f": {
			Piece:       "white_bishop",
			Selected:    false,
			Coordinates: [2]int{0, 500},
			Color:       "#f0d9b5",
		},
		"2f": {
			Piece:       "white_pawn",
			Selected:    false,
			Coordinates: [2]int{100, 500},
			Color:       "#b58863",
		},
		"3f": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{200, 500},
			Color:       "#f0d9b5",
		},
		"4f": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{300, 500},
			Color:       "#b58863",
		},
		"5f": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{400, 500},
			Color:       "#f0d9b5",
		},
		"6f": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{500, 500},
			Color:       "#b58863",
		},
		"7f": {
			Piece:       "black_pawn",
			Selected:    false,
			Coordinates: [2]int{600, 500},
			Color:       "#f0d9b5",
		},
		"8f": {
			Piece:       "black_bishop",
			Selected:    false,
			Coordinates: [2]int{700, 500},
			Color:       "#b58863",
		},
		"1g": {
			Piece:       "white_knight",
			Selected:    false,
			Coordinates: [2]int{0, 600},
			Color:       "#b58863",
		},
		"2g": {
			Piece:       "white_pawn",
			Selected:    false,
			Coordinates: [2]int{100, 600},
			Color:       "#f0d9b5",
		},
		"3g": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{200, 600},
			Color:       "#b58863",
		},
		"4g": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{300, 600},
			Color:       "#f0d9b5",
		},
		"5g": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{400, 600},
			Color:       "#b58863",
		},
		"6g": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{500, 600},
			Color:       "#f0d9b5",
		},
		"7g": {
			Piece:       "black_pawn",
			Selected:    false,
			Coordinates: [2]int{600, 600},
			Color:       "#b58863",
		},
		"8g": {
			Piece:       "black_knight",
			Selected:    false,
			Coordinates: [2]int{700, 600},
			Color:       "#f0d9b5",
		},
		"1h": {
			Piece:       "white_rook",
			Selected:    false,
			Coordinates: [2]int{0, 700},
			Color:       "#f0d9b5",
		},
		"2h": {
			Piece:       "white_pawn",
			Selected:    false,
			Coordinates: [2]int{100, 700},
			Color:       "#b58863",
		},
		"3h": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{200, 700},
			Color:       "#f0d9b5",
		},
		"4h": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{300, 700},
			Color:       "#b58863",
		},
		"5h": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{400, 700},
			Color:       "#f0d9b5",
		},
		"6h": {
			Piece:       "",
			Selected:    false,
			Coordinates: [2]int{500, 700},
			Color:       "#b58863",
		},
		"7h": {
			Piece:       "black_pawn",
			Selected:    false,
			Coordinates: [2]int{600, 700},
			Color:       "#f0d9b5",
		},
		"8h": {
			Piece:       "black_rook",
			Selected:    false,
			Coordinates: [2]int{700, 700},
			Color:       "#b58863",
		},
	}
	return board
}
