package main

import "github.com/NikolaTosic-sudo/chess-live/containers/components"

func getMockBoard() map[string]components.Square {
	return map[string]components.Square{
		"1a": {
			Selected:           false,
			Coordinates:        [2]int{0, 0},
			CoordinatePosition: [2]int{0, 0},
			Color:              "#b58863",
			Piece: components.Piece{
				Name:       "right_white_rook",
				Image:      "white_rook",
				Tile:       "1a",
				IsWhite:    true,
				LegalMoves: [][]int{{1, 0}, {0, 1}, {-1, 0}, {0, -1}},
				Moved:      false,
			},
		},
		"2a": {
			Selected:           false,
			Coordinates:        [2]int{1, 0},
			CoordinatePosition: [2]int{1, 0},
			Color:              "#f0d9b5",
			Piece: components.Piece{
				Name:       "white_pawn_1",
				Image:      "white_pawn",
				Tile:       "2a",
				IsWhite:    true,
				LegalMoves: [][]int{{-1, 0}},
				MovesOnce:  true,
				Moved:      false,
				IsPawn:     true,
			},
		},
		"3a": {
			Selected:           false,
			Coordinates:        [2]int{2, 0},
			CoordinatePosition: [2]int{2, 0},
			Color:              "#b58863",
		},
		"4a": {
			Selected:           false,
			Coordinates:        [2]int{3, 0},
			CoordinatePosition: [2]int{3, 0},
			Color:              "#f0d9b5",
		},
		"5a": {
			Selected:           false,
			Coordinates:        [2]int{4, 0},
			CoordinatePosition: [2]int{4, 0},
			Color:              "#b58863",
		},
		"6a": {
			Selected:           false,
			Coordinates:        [2]int{5, 0},
			CoordinatePosition: [2]int{5, 0},
			Color:              "#f0d9b5",
		},
		"7a": {
			Selected:           false,
			Coordinates:        [2]int{6, 0},
			CoordinatePosition: [2]int{6, 0},
			Color:              "#b58863",
		},
		"8a": {
			Selected:           false,
			Coordinates:        [2]int{7, 0},
			CoordinatePosition: [2]int{7, 0},
			Color:              "#f0d9b5",
		},
		"1b": {
			Selected:           false,
			Coordinates:        [2]int{0, 1},
			CoordinatePosition: [2]int{0, 1},
			Color:              "#f0d9b5",
			Piece: components.Piece{
				Name:       "right_white_knight",
				Image:      "white_knight",
				Tile:       "1b",
				IsWhite:    true,
				LegalMoves: [][]int{{2, 1}, {2, -1}, {1, 2}, {1, -2}, {-1, 2}, {-1, -2}, {-2, 1}, {-2, -1}},
				MovesOnce:  true,
				Moved:      false,
			},
		},
		"2b": {
			Selected:           false,
			Coordinates:        [2]int{1, 1},
			CoordinatePosition: [2]int{1, 1},
			Color:              "#b58863",
			Piece: components.Piece{
				Name:       "white_pawn_2",
				Image:      "white_pawn",
				Tile:       "2b",
				IsWhite:    true,
				LegalMoves: [][]int{{-1, 0}},
				MovesOnce:  true,
				Moved:      false,
				IsPawn:     true,
			},
		},
		"3b": {
			Selected:           false,
			Coordinates:        [2]int{2, 1},
			CoordinatePosition: [2]int{2, 1},
			Color:              "#f0d9b5",
		},
		"4b": {
			Selected:           false,
			Coordinates:        [2]int{3, 1},
			CoordinatePosition: [2]int{3, 1},
			Color:              "#b58863",
		},
		"5b": {
			Selected:           false,
			Coordinates:        [2]int{4, 1},
			CoordinatePosition: [2]int{4, 1},
			Color:              "#f0d9b5",
		},
		"6b": {
			Selected:           false,
			Coordinates:        [2]int{5, 1},
			CoordinatePosition: [2]int{5, 1},
			Color:              "#b58863",
		},
		"7b": {
			Selected:           false,
			Coordinates:        [2]int{6, 1},
			CoordinatePosition: [2]int{6, 1},
			Color:              "#f0d9b5",
		},
		"8b": {
			Selected:           false,
			Coordinates:        [2]int{7, 1},
			CoordinatePosition: [2]int{7, 1},
			Color:              "#b58863",
		},
		"1c": {
			Selected:           false,
			Coordinates:        [2]int{0, 2},
			CoordinatePosition: [2]int{0, 2},
			Color:              "#b58863",
			Piece: components.Piece{
				Name:       "right_white_bishop",
				Image:      "white_bishop",
				Tile:       "1c",
				IsWhite:    true,
				LegalMoves: [][]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}},
				Moved:      false,
			},
		},
		"2c": {
			Selected:           false,
			Coordinates:        [2]int{1, 2},
			CoordinatePosition: [2]int{1, 2},
			Color:              "#f0d9b5",
			Piece: components.Piece{
				Name:       "white_pawn_3",
				Image:      "white_pawn",
				Tile:       "2c",
				IsWhite:    true,
				LegalMoves: [][]int{{-1, 0}},
				MovesOnce:  true,
				Moved:      false,
				IsPawn:     true,
			},
		},
		"3c": {
			Selected:           false,
			Coordinates:        [2]int{2, 2},
			CoordinatePosition: [2]int{2, 2},
			Color:              "#b58863",
		},
		"4c": {
			Selected:           false,
			Coordinates:        [2]int{3, 2},
			CoordinatePosition: [2]int{3, 2},
			Color:              "#f0d9b5",
		},
		"5c": {
			Selected:           false,
			Coordinates:        [2]int{4, 2},
			CoordinatePosition: [2]int{4, 2},
			Color:              "#b58863",
		},
		"6c": {
			Selected:           false,
			Coordinates:        [2]int{5, 2},
			CoordinatePosition: [2]int{5, 2},
			Color:              "#f0d9b5",
		},
		"7c": {
			Selected:           false,
			Coordinates:        [2]int{6, 2},
			CoordinatePosition: [2]int{6, 2},
			Color:              "#b58863",
		},
		"8c": {
			Selected:           false,
			Coordinates:        [2]int{7, 2},
			CoordinatePosition: [2]int{7, 2},
			Color:              "#f0d9b5",
		},
		"1d": {
			Selected:           false,
			Coordinates:        [2]int{0, 3},
			CoordinatePosition: [2]int{0, 3},
			Color:              "#f0d9b5",
			Piece: components.Piece{
				Name:       "white_queen",
				Image:      "white_queen",
				Tile:       "1d",
				IsWhite:    true,
				LegalMoves: [][]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}, {1, 0}, {0, 1}, {-1, 0}, {0, -1}},
				Moved:      false,
			},
		},
		"2d": {
			Selected:           false,
			Coordinates:        [2]int{1, 3},
			CoordinatePosition: [2]int{1, 3},
			Color:              "#b58863",
			Piece: components.Piece{
				Name:       "white_pawn_4",
				Image:      "white_pawn",
				Tile:       "2d",
				IsWhite:    true,
				LegalMoves: [][]int{{-1, 0}},
				MovesOnce:  true,
				Moved:      false,
				IsPawn:     true,
			},
		},
		"3d": {
			Selected:           false,
			Coordinates:        [2]int{2, 3},
			CoordinatePosition: [2]int{2, 3},
			Color:              "#f0d9b5",
			Piece: components.Piece{
				Name:       "left_white_bishop",
				Image:      "white_bishop",
				Tile:       "3d",
				IsWhite:    true,
				LegalMoves: [][]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}},
				Moved:      true,
			},
		},
		"4d": {
			Selected:           false,
			Coordinates:        [2]int{3, 3},
			CoordinatePosition: [2]int{3, 3},
			Color:              "#b58863",
		},
		"5d": {
			Selected:           false,
			Coordinates:        [2]int{4, 3},
			CoordinatePosition: [2]int{4, 3},
			Color:              "#f0d9b5",
		},
		"6d": {
			Selected:           false,
			Coordinates:        [2]int{5, 3},
			CoordinatePosition: [2]int{5, 3},
			Color:              "#b58863",
		},
		"7d": {
			Selected:           false,
			Coordinates:        [2]int{6, 3},
			CoordinatePosition: [2]int{6, 3},
			Color:              "#f0d9b5",
		},
		"8d": {
			Selected:           false,
			Coordinates:        [2]int{7, 3},
			CoordinatePosition: [2]int{7, 3},
			Color:              "#b58863",
		},
		"1e": {
			Selected:           false,
			Coordinates:        [2]int{0, 4},
			CoordinatePosition: [2]int{0, 4},
			Color:              "#b58863",
			Piece: components.Piece{
				Name:       "white_king",
				Image:      "white_king",
				Tile:       "1e",
				IsWhite:    true,
				LegalMoves: [][]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}, {1, 0}, {0, 1}, {-1, 0}, {0, -1}},
				MovesOnce:  true,
				Moved:      false,
				IsKing:     true,
			},
		},
		"2e": {
			Selected:           false,
			Coordinates:        [2]int{1, 4},
			CoordinatePosition: [2]int{1, 4},
			Color:              "#f0d9b5",
		},
		"3e": {
			Selected:           false,
			Coordinates:        [2]int{2, 4},
			CoordinatePosition: [2]int{2, 4},
			Color:              "#b58863",
		},
		"4e": {
			Selected:           false,
			Coordinates:        [2]int{3, 4},
			CoordinatePosition: [2]int{3, 4},
			Color:              "#f0d9b5",
			Piece: components.Piece{
				Name:       "white_pawn_5",
				Image:      "white_pawn",
				Tile:       "4e",
				IsWhite:    true,
				LegalMoves: [][]int{{-1, 0}},
				MovesOnce:  true,
				Moved:      true,
				IsPawn:     true,
			},
		},
		"5e": {
			Selected:           false,
			Coordinates:        [2]int{4, 4},
			CoordinatePosition: [2]int{4, 4},
			Color:              "#b58863",
		},
		"6e": {
			Selected:           false,
			Coordinates:        [2]int{5, 4},
			CoordinatePosition: [2]int{5, 4},
			Color:              "#f0d9b5",
		},
		"7e": {
			Selected:           false,
			Coordinates:        [2]int{6, 4},
			CoordinatePosition: [2]int{6, 4},
			Color:              "#b58863",
		},
		"8e": {
			Selected:           false,
			Coordinates:        [2]int{7, 4},
			CoordinatePosition: [2]int{7, 4},
			Color:              "#f0d9b5",
		},
		"1f": {
			Selected:           false,
			Coordinates:        [2]int{0, 5},
			CoordinatePosition: [2]int{0, 5},
			Color:              "#f0d9b5",
		},
		"2f": {
			Selected:           false,
			Coordinates:        [2]int{1, 5},
			CoordinatePosition: [2]int{1, 5},
			Color:              "#b58863",
			Piece: components.Piece{
				Name:       "white_pawn_6",
				Image:      "white_pawn",
				Tile:       "2f",
				IsWhite:    true,
				LegalMoves: [][]int{{-1, 0}},
				MovesOnce:  true,
				Moved:      false,
				IsPawn:     true,
			},
		},
		"3f": {
			Selected:           false,
			Coordinates:        [2]int{2, 5},
			CoordinatePosition: [2]int{2, 5},
			Color:              "#f0d9b5",
			Piece: components.Piece{
				Name:       "left_white_knight",
				Image:      "white_knight",
				Tile:       "3f",
				IsWhite:    true,
				LegalMoves: [][]int{{2, 1}, {2, -1}, {1, 2}, {1, -2}, {-1, 2}, {-1, -2}, {-2, 1}, {-2, -1}},
				MovesOnce:  true,
				Moved:      true,
			},
		},
		"4f": {
			Selected:           false,
			Coordinates:        [2]int{3, 5},
			CoordinatePosition: [2]int{3, 5},
			Color:              "#b58863",
		},
		"5f": {
			Selected:           false,
			Coordinates:        [2]int{4, 5},
			CoordinatePosition: [2]int{4, 5},
			Color:              "#f0d9b5",
		},
		"6f": {
			Selected:           false,
			Coordinates:        [2]int{5, 5},
			CoordinatePosition: [2]int{5, 5},
			Color:              "#b58863",
		},
		"7f": {
			Selected:           false,
			Coordinates:        [2]int{6, 5},
			CoordinatePosition: [2]int{6, 5},
			Color:              "#f0d9b5",
		},
		"8f": {
			Selected:           false,
			Coordinates:        [2]int{7, 5},
			CoordinatePosition: [2]int{7, 5},
			Color:              "#b58863",
		},
		"1g": {
			Selected:           false,
			Coordinates:        [2]int{0, 6},
			CoordinatePosition: [2]int{0, 6},
			Color:              "#b58863",
		},
		"2g": {
			Selected:           false,
			Coordinates:        [2]int{1, 6},
			CoordinatePosition: [2]int{1, 6},
			Color:              "#f0d9b5",
			Piece: components.Piece{
				Name:       "white_pawn_7",
				Image:      "white_pawn",
				Tile:       "2g",
				IsWhite:    true,
				LegalMoves: [][]int{{-1, 0}},
				MovesOnce:  true,
				Moved:      false,
				IsPawn:     true,
			},
		},
		"3g": {
			Selected:           false,
			Coordinates:        [2]int{2, 6},
			CoordinatePosition: [2]int{2, 6},
			Color:              "#b58863",
		},
		"4g": {
			Selected:           false,
			Coordinates:        [2]int{3, 6},
			CoordinatePosition: [2]int{3, 6},
			Color:              "#f0d9b5",
		},
		"5g": {
			Selected:           false,
			Coordinates:        [2]int{4, 6},
			CoordinatePosition: [2]int{4, 6},
			Color:              "#b58863",
		},
		"6g": {
			Selected:           false,
			Coordinates:        [2]int{5, 6},
			CoordinatePosition: [2]int{5, 6},
			Color:              "#f0d9b5",
		},
		"7g": {
			Selected:           false,
			Coordinates:        [2]int{6, 6},
			CoordinatePosition: [2]int{6, 6},
			Color:              "#b58863",
		},
		"8g": {
			Selected:           false,
			Coordinates:        [2]int{7, 6},
			CoordinatePosition: [2]int{7, 6},
			Color:              "#f0d9b5",
		},
		"1h": {
			Selected:           false,
			Coordinates:        [2]int{0, 7},
			CoordinatePosition: [2]int{0, 7},
			Color:              "#f0d9b5",
			Piece: components.Piece{
				Name:       "left_white_rook",
				Image:      "white_rook",
				Tile:       "1h",
				IsWhite:    true,
				LegalMoves: [][]int{{1, 0}, {0, 1}, {-1, 0}, {0, -1}},
				Moved:      false,
			},
		},
		"2h": {
			Selected:           false,
			Coordinates:        [2]int{1, 7},
			CoordinatePosition: [2]int{1, 7},
			Color:              "#b58863",
			Piece: components.Piece{
				Name:       "white_pawn_8",
				Image:      "white_pawn",
				Tile:       "2h",
				IsWhite:    true,
				LegalMoves: [][]int{{-1, 0}},
				MovesOnce:  true,
				Moved:      false,
				IsPawn:     true,
			},
		},
		"3h": {
			Selected:           false,
			Coordinates:        [2]int{2, 7},
			CoordinatePosition: [2]int{2, 7},
			Color:              "#f0d9b5",
		},
		"4h": {
			Selected:           false,
			Coordinates:        [2]int{3, 7},
			CoordinatePosition: [2]int{3, 7},
			Color:              "#b58863",
		},
		"5h": {
			Selected:           false,
			Coordinates:        [2]int{4, 7},
			CoordinatePosition: [2]int{4, 7},
			Color:              "#f0d9b5",
		},
		"6h": {
			Selected:           false,
			Coordinates:        [2]int{5, 7},
			CoordinatePosition: [2]int{5, 7},
			Color:              "#b58863",
		},
		"7h": {
			Selected:           false,
			Coordinates:        [2]int{6, 7},
			CoordinatePosition: [2]int{6, 7},
			Color:              "#f0d9b5",
		},
		"8h": {
			Selected:           false,
			Coordinates:        [2]int{7, 7},
			CoordinatePosition: [2]int{7, 7},
			Color:              "#b58863",
		},
	}
}

func getMockMatchCastle() Match {
	return Match{
		board: getMockBoard(),
		selectedPiece: components.Piece{
			Name:       "white_king",
			Image:      "white_king",
			Tile:       "1e",
			IsWhite:    true,
			LegalMoves: [][]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}, {1, 0}, {0, 1}, {-1, 0}, {0, -1}},
			MovesOnce:  true,
			Moved:      false,
			IsKing:     true,
		},
	}
}

func getMockMatchMovesKnight() Match {
	return Match{
		board: getMockBoard(),
		selectedPiece: components.Piece{
			Name:       "left_white_knight",
			Image:      "white_knight",
			Tile:       "3f",
			IsWhite:    true,
			LegalMoves: [][]int{{2, 1}, {2, -1}, {1, 2}, {1, -2}, {-1, 2}, {-1, -2}, {-2, 1}, {-2, -1}},
			MovesOnce:  true,
			Moved:      true,
		},
	}
}
